<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerORplKM2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerORplKM2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerORplKM2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerORplKM2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerORplKM2\App_KernelDevDebugContainer([
    'container.build_hash' => 'ORplKM2',
    'container.build_id' => '77cefb81',
    'container.build_time' => 1634302507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerORplKM2');
